### ISSUE TITLE
Request for License Change to MIT

### ISSUE THREAD

**Issue by harshu4** [bruno353/dpl-backend#6]
**Request:**
We kindly request all contributors to respond to this issue with one of the following:
- **ack**: I approve the license change to MIT.
- **nack**: I do not approve the license change to MIT.

**Response Deadline:**
Please respond by 14/07/2024. If no response is received by then, it will be assumed that you approve ("ack") of the license change.

Thank you for your attention to this matter.

@bruno353 @dowdt @harrys522 @harshu4

**Comment by bruno353** [comment]
ack

**Comment by harrys522** [comment]
ack

**Comment by dowdt** [comment]
ack

**Comment by harrys522** [comment]
I approve MIT. ack

**Comment by harshu4** [comment]
Ack

**Comment by dowdt** [comment]
All contributors acknowldeged. Adding license.
![image](https://github.com/user-attachments/assets/b1ec3a34-fc10-4e05-92e7-986500c8170e)
